<?php
$_product = Mage::registry('current_product');
$attachments = $this->getProductAttachments($_product->getId());
if (count($attachments) > 0):
    ?>
    <h2><?php echo $this->__('Product Attachments') ?></h2>
    <div class="collateral-box attachment-specs">
        <table cellspacing="0" id="product-attachment-specs-table" class="data-table">
            <tbody>
            <?php foreach ($attachments as $attachment): ?>
                <tr>
                    <td class="label"><?php echo $attachment['file']; ?></td>
                    <td class="data"><?php echo $attachment['content']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
